import "./globals.css";
import { Inter } from "next/font/google";
import { Providers } from "../../providers";
import Navbar11 from "./navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "CourseMate",
  description: "Generated by create next app",
  
};

export const viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  // Also supported by less commonly used
  // interactiveWidget: 'resizes-visual',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar11 />
        <Providers>{children}</Providers>
        
      </body>
    </html>
  );
}
